"""initial_schema

Revision ID: a6f6dd1e6d0b
Revises: 
Create Date: 2026-06-15 13:24:59.884812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f6dd1e6d0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('governance_report_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('governance_trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('maturity_score', sa.Integer(), nullable=False),
    sa.Column('risk_exposure', sa.Integer(), nullable=False),
    sa.Column('mitigation_effectiveness_pct', sa.Float(), nullable=False),
    sa.Column('sla_breaches', sa.Integer(), nullable=False),
    sa.Column('open_escalations', sa.Integer(), nullable=False),
    sa.Column('verified_mitigations', sa.Integer(), nullable=False),
    sa.Column('critical_risks', sa.Integer(), nullable=False),
    sa.Column('notification_volume', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_trend_snapshots_id'), 'governance_trend_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_governance_trend_snapshots_timestamp'), 'governance_trend_snapshots', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_role', sa.String(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('read_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('teams_webhook_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('governance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('governance_relevance', sa.String(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_reports_id'), 'governance_reports', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workflow_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('logs', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_jobs_id'), 'workflow_jobs', ['id'], unique=False)
    op.create_table('escalation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('routing_target', sa.String(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raised_by', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('remediation_plan', sa.Text(), nullable=True),
    sa.Column('expected_risk_reduction', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('suggested_owner_role', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('explainability_trace', sa.Text(), nullable=True),
    sa.Column('explain_why', sa.Text(), nullable=True),
    sa.Column('suggested_actions', sa.Text(), nullable=True),
    sa.Column('estimated_impact', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['governance_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_items_id'), 'escalation_items', ['id'], unique=False)
    op.create_table('meeting_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['governance_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_actions_id'), 'meeting_actions', ['id'], unique=False)
    op.create_table('raid_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recommended_mitigations', sa.Text(), nullable=True),
    sa.Column('implementation_effort', sa.String(), nullable=True),
    sa.Column('expected_risk_reduction', sa.String(), nullable=True),
    sa.Column('recommended_priority', sa.String(), nullable=True),
    sa.Column('suggested_owner_role', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('current_risk_score', sa.Integer(), nullable=False),
    sa.Column('explainability_trace', sa.Text(), nullable=True),
    sa.Column('explain_why', sa.Text(), nullable=True),
    sa.Column('suggested_actions', sa.Text(), nullable=True),
    sa.Column('estimated_impact', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['governance_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_items_id'), 'raid_items', ['id'], unique=False)
    op.create_table('mitigation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_raid_item_id', sa.Integer(), nullable=False),
    sa.Column('related_escalation_id', sa.Integer(), nullable=True),
    sa.Column('owner_role', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.String(), nullable=True),
    sa.Column('sla_status', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('effectiveness', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_escalation_id'], ['escalation_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_raid_item_id'], ['raid_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitigation_tasks_id'), 'mitigation_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mitigation_tasks_id'), table_name='mitigation_tasks')
    op.drop_table('mitigation_tasks')
    op.drop_index(op.f('ix_raid_items_id'), table_name='raid_items')
    op.drop_table('raid_items')
    op.drop_index(op.f('ix_meeting_actions_id'), table_name='meeting_actions')
    op.drop_table('meeting_actions')
    op.drop_index(op.f('ix_escalation_items_id'), table_name='escalation_items')
    op.drop_table('escalation_items')
    op.drop_index(op.f('ix_workflow_jobs_id'), table_name='workflow_jobs')
    op.drop_table('workflow_jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_governance_reports_id'), table_name='governance_reports')
    op.drop_table('governance_reports')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_governance_trend_snapshots_timestamp'), table_name='governance_trend_snapshots')
    op.drop_index(op.f('ix_governance_trend_snapshots_id'), table_name='governance_trend_snapshots')
    op.drop_table('governance_trend_snapshots')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
